# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RXAcNJ39YjvLdX8JBFub8mnKgEbcVAX2
"""

import random

choices = {
    "r": "rock",
    "p": "paper",
    "s": "scissors"
}

print("✊ Rock Paper Scissors")
print("Type: r = rock, p = paper, s = scissors, q = quit")

while True:
    user = input("Enter choice: ").lower()

    if user == "q":
        print("Game Over 👋")
        break

    if user not in choices:
        print("Invalid input! Use r, p, or s.")
        continue

    computer = random.choice(list(choices.values()))
    user_choice = choices[user]

    print("You chose:", user_choice)
    print("Computer chose:", computer)

    if user_choice == computer:
        print("It's a Draw!")
    elif (user_choice == "rock" and computer == "scissors") or \
         (user_choice == "paper" and computer == "rock") or \
         (user_choice == "scissors" and computer == "paper"):
        print("🎉 You Win!")
    else:
        print("🤖 Computer Wins!")

    print("-" * 30)

